# cyberlab.toml
#
# Copyright: 2023 Antonio Voza
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-only
#
#
#
# This file is intended for configuring your docker container labs in Athena Cyber Hub (ACH).
#
## Structure of the content
#
# id: replace with the container image ID (getting from 'docker ps -a' under IMAGE NAMES column after building or pulling your image)
# name: set your favourite name
# path_docker: path to the docker-compose.yml file
# path_readme: path to the markdown file containing information about the lab
#

[[environment]]
id = "container-hub/dummylab"
name = "Container 1"
path_docker = "/path/to/docker-compose.yml"
path_readme = "/path/to/README.md"

[[environment]]
id = "well-hub/yourlab"
name = "Container 2"
path_docker = "/path/to/docker-compose.yml"
path_readme = "/path/to/README.md"
